# Generated by Django 3.1.4 on 2020-12-31 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='company.company'),
        ),
    ]
