# Generated by Django 3.1.4 on 2020-12-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0003_auto_20201231_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='company.company'),
        ),
    ]
