# Generated by Django 3.1.4 on 2021-01-03 12:47

from django.db import migrations, models
import menu.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('type', models.IntegerField(choices=[(menu.enums.EnumTypeMenu['APP'], '0')])),
                ('active', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SFT_MENU',
            },
        ),
    ]
