# Generated by Django 3.1.4 on 2020-12-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='users',
            field=models.ManyToManyField(blank=True, to='user.User'),
        ),
    ]
