# Generated by Django 3.1.4 on 2021-01-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
